INSERT INTO Szakterulet (`szakterulet_nev`)
VALUES ('Országos Főigazgató'),
       ('Kórházigazgató'),
       ('Belgyógyászat'),
       ('Bőrgyógyászat'),
       ('Dietetika'),
       ('Endokrinológia'),
       ('Érsebészet'),
       ('Fül-Orr-Gégészet'),
       ('Gasztroenterológia'),
       ('Gyermeksebészet'),
       ('Hematológia'),
       ('Idegsebészet'),
       ('Kardiológia'),
       ('Kézsebészet'),
       ('Neurológia'),
       ('Nőgyógyászat'),
       ('Ortopédia'),
       ('Plasztikai Sebészet'),
       ('Pulmonológia'),
       ('Reumatológia'),
       ('Sebészet'),
       ('Szemészet'),
       ('Szülészet-nőgyógyászat'),
       ('Urológia');