= Követelmény specifikáció

[cols="5,3,2"]

|===
|Követelmény |Használati esetek |Állapot

| *Kórházak kezelése*

    Kiválasztott kórház metaadatainak megtekintése

    Új kórház rögzítése a rendszerben

    Kiválasztott kórház metaadatainak módosítása

    Az esetlegesen megszűnt kórházak törlése a rendszerből

    A rendszerben lévő kórházak listázása

|
* Kórház megtekintése

* Kórház létrehozása

* Kórház módosítása

* Kórház törlése

* Kórházak listázása

| Elkészítve

| *Orvosok kezelése*

    Kiválasztott orvos metaadatainak megtekintése

    Új orvos rögzítése a rendszerben

    Kiválasztott orvos metaadatainak módosítása

    A távozó orvosok törlése a rendszerből

    A rendszerben lévő orvosok listázása

    A rendszerben lévő orvosok szűrése kórház alapján

    A rendszerben lévő orvosok szűrése kórház és szakterület alapján

|
* Orvos megtekintése

* Orvos létrehozása

* Orvos módosítása

* Orvos törlése

* Orvosok listázása

* Orvosok szűrése kórház szerint

* Orvosok szűrése kórház és szakterület szerint

| Elkészítve

| *Szolgáltatások kezelése*

    Kiválasztott szolgáltatás metaadatainak megtekintése

    Új szolgáltatás rögzítése a rendszerben

    Kiválasztott szolgáltatás metaadatainak módosítása

    Az esetlegesen megszűnt vagy kifutott szolgáltatás törlése a rendszerből

    A rendszerben lévő szolgáltatások listázása

|
* Szolgáltatás megtekintése

* Szolgáltatás létrehozása

* Szolgáltatás módosítása

* Szolgáltatás törlése

* Szolgáltatások listázása

| Elkészítve

| *Időpontok kezelése*

    Kiválasztott időpont metaadatainak megtekintése

    Időpont foglalása

    Lemondás vagy váratlan esemény esetén időpont törlése

    A lefoglalt időpontok listázása

|
* Időpont megtekintése

* Időpont foglalása

* Időpont törlése

* Időpontok listázása

| Elkészítve

| *Szakterületek kezelése*

    Kiválasztott szakterület metaadatainak megtekintése

    Új szakterület rögzítése a rendszerben

    Az esetlegesen elavult vagy megszűnt szakterület törlése a rendszerből

    A rendszerben lévő szakterületek listázása

|
* Szakterület megtekintése

* Szakterület létrehozása

* Szakterület törlése

* Szakterület listázása

| Elkészítve

| *Felhasználók kezelése*

    Kiválasztott felhasználó metaadatainak megtekintése

    Új felhasználó rögzítése a rendszerben

    Kiválasztott felhasználó metaadatainak módosítása

    Felhasználó törlése a rendszerből

    A rendszerben lévő felhasználók listázása

|
* Felhasználó megtekintése

* Felhasználó létrehozása

* Felhasználó módosítása

* Felhasználó törlése

* Felhasználók listázása

| Elkészítve

|   A rendszerben bizonyos funkciók csak bejelentkezést követően lesznek elérhetők.

    Bejelentkezni csak adminisztrátori szerepkörbe lehet, megadott felhasználónévvel és jelszóval

    Az alábbi használati esetek csak bejelentkezést követően, admin felületen érhetőek el:

* Kórház létrehozása

* Kórház módosítása

* Kórház törlése

* Orvos létrehozása

* Orvos módosítása

* Orvos törlése

* Szolgáltatás létrehozása

* Szolgáltatás módosítása

* Szolgáltatás törlése

* Időpontok listázása

* Időpont törlése

* Szakterület létrehozása

* Szakterület törlése

* Felhasználó megtekintése

* Felhasználó létrehozása

* Felhasználó módosítása

* Felhasználó törlése

* Felhasználók listázása

|
* Adminisztrátori bejelentkezés

| Elkészítve

|===

link:../../README.adoc[Vissza]