-- MySQL Script generated by MySQL Workbench
-- Thu Jan 30 14:26:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Felhasznalo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Felhasznalo` (
  `felhasznalo_id` INT NOT NULL AUTO_INCREMENT,
  `felhasznalo_nev` VARCHAR(45) NOT NULL,
  `jelszo` VARCHAR(45) NOT NULL,
  `teljes_nev` VARCHAR(45) NOT NULL,
  `admin` INT NOT NULL,
  PRIMARY KEY (`felhasznalo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Szakterulet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Szakterulet` (
  `szakterulet_id` INT NOT NULL AUTO_INCREMENT,
  `szakterulet_nev` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`szakterulet_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Korhaz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Korhaz` (
  `korhaz_id` INT NOT NULL AUTO_INCREMENT,
  `korhaz_nev` VARCHAR(45) NOT NULL,
  `korhaz_cim` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`korhaz_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orvos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orvos` (
  `orvos_id` INT NOT NULL AUTO_INCREMENT,
  `nev` VARCHAR(45) NOT NULL,
  `korhaz_id` INT NOT NULL,
  `telefonszam` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `szakterulet_id` INT NOT NULL,
  `kep_nev` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`orvos_id`),
  INDEX `fk_Orvos_Szakterulet1_idx` (`szakterulet_id` ASC) VISIBLE,
  INDEX `fk_Orvos_Korhaz1_idx` (`korhaz_id` ASC) VISIBLE,
  CONSTRAINT `fk_Orvos_Szakterulet1`
    FOREIGN KEY (`szakterulet_id`)
    REFERENCES `mydb`.`Szakterulet` (`szakterulet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orvos_Korhaz1`
    FOREIGN KEY (`korhaz_id`)
    REFERENCES `mydb`.`Korhaz` (`korhaz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Velemeny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Velemeny` (
  `velemeny_id` INT NOT NULL AUTO_INCREMENT,
  `velemeny_text` VARCHAR(45) NOT NULL,
  `felhasznalo_id` INT NOT NULL,
  `orvos_id` INT NOT NULL,
  `bejegyzes_ido` DATETIME NOT NULL,
  PRIMARY KEY (`velemeny_id`),
  INDEX `fk_Velemeny_Felhasznalo1_idx` (`felhasznalo_id` ASC) VISIBLE,
  INDEX `fk_Velemeny_Orvos1_idx` (`orvos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Velemeny_Felhasznalo1`
    FOREIGN KEY (`felhasznalo_id`)
    REFERENCES `mydb`.`Felhasznalo` (`felhasznalo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Velemeny_Orvos1`
    FOREIGN KEY (`orvos_id`)
    REFERENCES `mydb`.`Orvos` (`orvos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Szolgaltatas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Szolgaltatas` (
  `szolgaltatas_id` INT NOT NULL AUTO_INCREMENT,
  `szolgaltatas_nev` VARCHAR(45) NOT NULL,
  `szakterulet_id` INT NOT NULL,
  `ar` INT NOT NULL,
  PRIMARY KEY (`szolgaltatas_id`),
  INDEX `fk_Szolgaltatas_Szakterulet1_idx` (`szakterulet_id` ASC) VISIBLE,
  CONSTRAINT `fk_Szolgaltatas_Szakterulet1`
    FOREIGN KEY (`szakterulet_id`)
    REFERENCES `mydb`.`Szakterulet` (`szakterulet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Idopont`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Idopont` (
  `idopont_id` INT NOT NULL AUTO_INCREMENT,
  `ido` DATETIME NOT NULL,
  `felhasznalo_id` INT NOT NULL,
  `orvos_id` INT NOT NULL,
  `korhaz_id` INT NOT NULL,
  `szolgaltatas_id` INT NOT NULL,
  PRIMARY KEY (`idopont_id`),
  INDEX `fk_Idopont_Felhasznalo_idx` (`felhasznalo_id` ASC) VISIBLE,
  INDEX `fk_Idopont_Orvos1_idx` (`orvos_id` ASC) VISIBLE,
  INDEX `fk_Idopont_Korhaz1_idx` (`korhaz_id` ASC) VISIBLE,
  INDEX `fk_Idopont_Szolgaltatas1_idx` (`szolgaltatas_id` ASC) VISIBLE,
  CONSTRAINT `fk_Idopont_Felhasznalo`
    FOREIGN KEY (`felhasznalo_id`)
    REFERENCES `mydb`.`Felhasznalo` (`felhasznalo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Idopont_Orvos1`
    FOREIGN KEY (`orvos_id`)
    REFERENCES `mydb`.`Orvos` (`orvos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Idopont_Korhaz1`
    FOREIGN KEY (`korhaz_id`)
    REFERENCES `mydb`.`Korhaz` (`korhaz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Idopont_Szolgaltatas1`
    FOREIGN KEY (`szolgaltatas_id`)
    REFERENCES `mydb`.`Szolgaltatas` (`szolgaltatas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
