-- MySQL Script generated by MySQL Workbench
-- Thu Jan 30 14:26:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema luxmed
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema luxmed
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `luxmed` DEFAULT CHARACTER SET utf8 ;
USE `luxmed` ;

-- -----------------------------------------------------
-- Table `luxmed`.`Felhasznalo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luxmed`.`Felhasznalo` (
  `felhasznalo_id` INT NOT NULL AUTO_INCREMENT,
  `felhasznalo_nev` VARCHAR(45) NOT NULL,
  `jelszo` VARCHAR(45) NOT NULL,
  `teljes_nev` VARCHAR(45) NOT NULL,
  `admin` INT NOT NULL,
  PRIMARY KEY (`felhasznalo_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `luxmed`.`Szakterulet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luxmed`.`Szakterulet` (
  `szakterulet_id` INT NOT NULL AUTO_INCREMENT,
  `szakterulet_nev` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`szakterulet_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Dummy `luxmed`.`Szakterulet`
-- -----------------------------------------------------
INSERT INTO `luxmed`.`Szakterulet` (`szakterulet_nev`) VALUES 
    ('Országos Főigazgató'),
    ('Kórházigazgató'),
    ('Belgyógyászat'),
    ('Bőrgyógyászat'),
    ('Dietetika'),
    ('Endokrinológia'),
    ('Érsebészet'),
    ('Fül-Orr-Gégészet'),
    ('Gasztroenterológia'),
    ('Gyermeksebészet'),
    ('Hematológia'),
    ('Idegsebészet'),
    ('Kardiológia'),
    ('Kézsebészet'),
    ('Neurológia'),
    ('Nőgyógyászat'),
    ('Ortopédia'),
    ('Plasztikai Sebészet'),
    ('Pulmonológia'),
    ('Reumatológia'),
    ('Sebészet'),
    ('Szemészet'),
    ('Szülészet-nőgyógyászat'),
    ('Urológia');

-- -----------------------------------------------------
-- Table `luxmed`.`Korhaz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luxmed`.`Korhaz` (
  `korhaz_id` INT NOT NULL AUTO_INCREMENT,
  `korhaz_nev` VARCHAR(45) NOT NULL,
  `korhaz_cim` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`korhaz_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Dummy `luxmed`.`Korhaz`
-- -----------------------------------------------------
INSERT INTO `luxmed`.`Korhaz` (`korhaz_nev`, `korhaz_cim`) VALUES 
    ('LuxMed Nyíregyháza', '4400 Nyíregyháza, Szabolcs utca 12.'),
    ('LuxMed Pest', '1106 Budapest, Üllői út 132.'),
    ('LuxMed Buda', '1117 Budapest, Bartók Béla út 74.'),
    ('LuxMed Debrecen', '4025 Debrecen, Piac utca 45.'),
    ('LuxMed Szeged', '6720 Szeged, Kárász utca 33.'),
    ('LuxMed Pécs', '7621 Pécs, Jókai utca 18.'),
    ('LuxMed Győr', '9021 Győr, Arany János utca 10.'),
    ('LuxMed Miskolc', '3530 Miskolc, Szent István út 8.');

-- -----------------------------------------------------
-- Table `luxmed`.`Orvos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luxmed`.`Orvos` (
  `orvos_id` INT NOT NULL AUTO_INCREMENT,
  `nev` VARCHAR(45) NOT NULL,
  `kep_nev` VARCHAR(45) NOT NULL,
  `szakterulet_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefonszam` VARCHAR(45) NOT NULL,
  `korhaz_id` INT NOT NULL,
  PRIMARY KEY (`orvos_id`),
  INDEX `fk_Orvos_Szakterulet1_idx` (`szakterulet_id` ASC) VISIBLE,
  INDEX `fk_Orvos_Korhaz1_idx` (`korhaz_id` ASC) VISIBLE,
  CONSTRAINT `fk_Orvos_Szakterulet1`
    FOREIGN KEY (`szakterulet_id`)
    REFERENCES `luxmed`.`Szakterulet` (`szakterulet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orvos_Korhaz1`
    FOREIGN KEY (`korhaz_id`)
    REFERENCES `luxmed`.`Korhaz` (`korhaz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Dummy `luxmed`.`Orvos`
-- -----------------------------------------------------

INSERT INTO `luxmed`.`Orvos` (`nev`, `kep_nev`, `szakterulet_id`, `email`, `telefonszam`, `korhaz_id`) VALUES 
	('Dr. Kopasz Tibor', '1.jpg', 1, 'foigazgato@luxmed.hu', '+36 20 376 7664', 2),
	('Dr. Szabó Tamás', '2.jpg', 2, 'szabo.tamas@luxmed.hu', '+36 20 456 7890', 1),
	('Dr. Varga Péter', '3.jpg', 2, 'varga.peter@luxmed.hu', '+36 30 876 5435', 2),
	('Dr. Kiss Anikó', '4.jpg', 2, 'kiss.aniko@luxmed.hu', '+36 70 234 5678', 3),
	('Dr. Kovács Éva', '5.jpg', 2, 'kovacs.eva@luxmed.hu', '+36 30 987 6543', 4),
	('Dr. Farkas Dóra', '6.jpg', 2, 'farkas.dora@luxmed.hu', '+36 20 654 3210', 5),
	('Dr. Horváth Katalin', '7.jpg', 2, 'horvath.katalin@luxmed.hu', '+36 30 543 2109', 6),
	('Dr. Nagy László', '8.jpg', 2, 'nagy.laszlo@luxmed.hu', '+36 20 789 0123', 7),
	('Dr. Tóth Gábor', '9.jpg', 2, 'toth.gabor@luxmed.hu', '+36 70 123 4567', 8),
	('Dr. Kiss Péter', '10.jpg', 3, 'kiss.peter@luxmed.hu', '+36 20 789 1234', 1),
	('Dr. Németh Anna', '11.jpg', 4, 'nemeth.anna@luxmed.hu', '+36 30 456 7890', 1),
	('Dr. Szalai Júlia', '12.jpg', 5, 'szalai.julia@luxmed.hu', '+36 70 654 3210', 1),
	('Dr. Balogh Tamás', '13.jpg', 6, 'balogh.tamas@luxmed.hu', '+36 20 876 5432', 1),
	('Dr. Horváth András', '14.jpg', 7, 'horvath.andras@luxmed.hu', '+36 30 345 6789', 1),
	('Dr. Varga László', '15.jpg', 7, 'varga.laszlo@luxmed.hu', '+36 20 543 2109', 1),
	('Dr. Szabad Judit', '16.jpg', 8, 'szabad.judit@luxmed.hu', '+36 70 876 5432', 1),
	('Dr. Szabados Ákos', '17.jpg', 9, 'szabados.akos@luxmed.hu', '+36 20 789 0123', 1),
	('Dr. Tóth Zsófia', '18.jpg', 10, 'toth.zsofia@luxmed.hu', '+36 30 345 6781', 1),
	('Dr. Nagy Attila', '19.jpg', 11, 'nagy.attila@luxmed.hu', '+36 70 456 7892', 1),
	('Dr. Kovács László', '20.jpg', 12, 'kovacs.laszlo@luxmed.hu', '+36 20 567 8901', 1),
	('Dr. Fekete Zoltán', '21.jpg', 13, 'fekete.zoltan@luxmed.hu', '+36 30 678 1234', 1),
	('Dr. Hegedűs Klára', '22.jpg', 13, 'hegedus.klara@luxmed.hu', '+36 70 543 2108', 1),
	('Dr. Szilágyi Tamás', '23.jpg', 14, 'szilagyi.tamas@luxmed.hu', '+36 20 345 6789', 1),
	('Dr. Bíró Katalin', '24.jpg', 15, 'biro.katalin@luxmed.hu', '+36 30 654 3212', 1),
	('Dr. Sárközi Ferenc', '25.jpg', 15, 'sarkozi.ferenc@luxmed.hu', '+36 70 567 8901', 1),
	('Dr. Horváth Bence', '26.jpg', 16, 'horvath.bence@luxmed.hu', '+36 20 789 3456', 1),
	('Dr. Lőrincz Dóra', '27.jpg', 16, 'lorincz.dora@luxmed.hu', '+36 30 456 7891', 1),
	('Dr. Fodor Péter', '28.jpg', 17, 'fodor.peter@luxmed.hu', '+36 70 345 6782', 1),
	('Dr. Kovács Milán', '29.jpg', 18, 'kovacs.milan@luxmed.hu', '+36 20 567 8902', 1),
	('Dr. Veres Ágnes', '30.jpg', 19, 'veres.agnes@luxmed.hu', '+36 30 789 0124', 1),
	('Dr. Török Sándor', '31.jpg', 20, 'torok.sandor@luxmed.hu', '+36 70 543 2107', 1),
	('Dr. Szűcs István', '32.jpg', 21, 'szucs.istvan@luxmed.hu', '+36 20 876 5431', 1),
	('Dr. Csonka Lilla', '33.jpg', 21, 'csonka.lilla@luxmed.hu', '+36 30 678 1230', 1),
	('Dr. Papp Mária', '34.jpg', 22, 'papp.maria@luxmed.hu', '+36 70 345 6783', 1),
	('Dr. Sárosi Éva', '35.jpg', 23, 'sarosi.eva@luxmed.hu', '+36 20 789 0120', 1),
	('Dr. Balogh Attila', '36.jpg', 24, 'balogh.attila@luxmed.hu', '+36 30 654 3211', 1),
	('Dr. Varga István', '37.jpg', 3, 'varga.istvan@luxmed.hu', '+36 20 987 6543', 2),
	('Dr. Tóth Ilona', '38.jpg', 4, 'toth.ilona@luxmed.hu', '+36 30 654 7890', 2),
	('Dr. Mészáros Gabriella', '39.jpg', 5, 'meszaros.gabriella@luxmed.hu', '+36 70 765 4321', 2),
	('Dr. Németh Tamás', '40.jpg', 6, 'nemeth.tamas@luxmed.hu', '+36 20 432 1098', 2),
	('Dr. Papp Zoltán', '41.jpg', 7, 'papp.zoltan@luxmed.hu', '+36 30 567 8902', 2),
	('Dr. Molnár Béla', '42.jpg', 7, 'molnar.bela@luxmed.hu', '+36 20 876 5430', 2),
	('Dr. Kiss Melinda', '43.jpg', 8, 'kiss.melinda@luxmed.hu', '+36 70 543 2107', 2),
	('Dr. Sipos László', '44.jpg', 9, 'sipos.laszlo@luxmed.hu', '+36 20 678 9012', 2),
	('Dr. Farkas Mária', '45.jpg', 10, 'farkas.maria@luxmed.hu', '+36 30 234 5678', 2),
	('Dr. Simon József', '46.jpg', 11, 'simon.jozsef@luxmed.hu', '+36 70 987 6543', 2),
	('Dr. Kováts Ágnes', '47.jpg', 12, 'kovats.agnes@luxmed.hu', '+36 20 765 4321', 2),
	('Dr. Varga András', '48.jpg', 13, 'varga.andras@luxmed.hu', '+36 30 678 9012', 2),
	('Dr. Szilágyi Zoltán', '49.jpg', 13, 'szilagyi.zoltan@luxmed.hu', '+36 70 543 2109', 2),
	('Dr. Sárközi Péter', '50.jpg', 14, 'sarkozi.peter@luxmed.hu', '+36 20 234 5678', 2),
	('Dr. Kovács László', '51.jpg', 15, 'kovacs.laszlo@luxmed.hu', '+36 30 678 9013', 2),
	('Dr. Sárosi Zsófia', '52.jpg', 15, 'sarosi.zsofia@luxmed.hu', '+36 70 765 4322', 2),
	('Dr. Fodor Éva', '53.jpg', 16, 'fodor.eva@luxmed.hu', '+36 20 456 7890', 2),
	('Dr. Juhász Péter', '54.jpg', 16, 'juhasz.peter@luxmed.hu', '+36 30 567 8903', 2),
	('Dr. Kiss Gábor', '55.jpg', 17, 'kiss.gabor@luxmed.hu', '+36 70 432 1098', 2),
	('Dr. Rácz Zoltán', '56.jpg', 18, 'racz.zoltan@luxmed.hu', '+36 20 678 9013', 2),
	('Dr. Császár Balázs', '57.jpg', 19, 'csaszar.balazs@luxmed.hu', '+36 30 234 5679', 2),
	('Dr. Szabó Mónika', '58.jpg', 20, 'szabo.monika@luxmed.hu', '+36 70 876 5433', 2),
	('Dr. László Tamás', '59.jpg', 21, 'laszlo.tamas@luxmed.hu', '+36 20 567 8904', 2),
	('Dr. Horváth Gabriella', '60.jpg', 21, 'horvath.gabriella@luxmed.hu', '+36 30 789 0125', 2),
	('Dr. Kósa János', '61.jpg', 22, 'kosa.janos@luxmed.hu', '+36 70 876 5434', 2),
	('Dr. László Anikó', '62.jpg', 23, 'laszlo.aniko@luxmed.hu', '+36 20 789 0126', 2),
	('Dr. Oláh Péter', '63.jpg', 24, 'olah.peter@luxmed.hu', '+36 30 654 3213', 2),
	('Dr. Kiss Márton', '64.jpg', 3, 'kiss.marton@luxmed.hu', '+36 20 789 2345', 3),
	('Dr. Pásztor Ilona', '65.jpg', 4, 'pasztor.ilona@luxmed.hu', '+36 30 876 5432', 3),
	('Dr. Kovács Gábor', '66.jpg', 5, 'kovacs.gabor@luxmed.hu', '+36 70 654 3213', 3),
	('Dr. Szeifert László', '67.jpg', 6, 'szeifert.laszlo@luxmed.hu', '+36 20 123 4567', 3),
	('Dr. Takács Erika', '68.jpg', 7, 'takacs.erika@luxmed.hu', '+36 30 234 5678', 3),
	('Dr. Tóth János', '69.jpg', 7, 'toth.janos@luxmed.hu', '+36 70 987 6543', 3),
	('Dr. Horváth Katalin', '70.jpg', 8, 'horvath.katalin@luxmed.hu', '+36 20 876 5431', 3),
	('Dr. Sánta Zoltán', '71.jpg', 9, 'santa.zoltan@luxmed.hu', '+36 30 432 1098', 3),
	('Dr. Molnár Piroska', '72.jpg', 10, 'molnar.piroska@luxmed.hu', '+36 70 567 8904', 3),
	('Dr. Farkas János', '73.jpg', 11, 'farkas.janos@luxmed.hu', '+36 20 654 3210', 3),
	('Dr. Varga Andrea', '74.jpg', 12, 'varga.andrea@luxmed.hu', '+36 30 765 4321', 3),
	('Dr. Pál Dániel', '75.jpg', 13, 'pal.daniel@luxmed.hu', '+36 70 432 1099', 3),
	('Dr. Balázs Viktória', '76.jpg', 13, 'balazs.viktoria@luxmed.hu', '+36 20 987 6542', 3),
	('Dr. Rácz Gábor', '77.jpg', 14, 'racz.gabor@luxmed.hu', '+36 30 234 5679', 3),
	('Dr. Csilla Éva', '78.jpg', 15, 'csilla.eva@luxmed.hu', '+36 70 654 3214', 3),
	('Dr. László Mária', '79.jpg', 15, 'laszlo.maria@luxmed.hu', '+36 20 123 4568', 3),
	('Dr. Szabó Zoltán', '80.jpg', 16, 'szabo.zoltan@luxmed.hu', '+36 30 234 5670', 3),
	('Dr. Földi István', '81.jpg', 16, 'foldi.istvan@luxmed.hu', '+36 70 876 5435', 3),
	('Dr. Lipták Gábor', '82.jpg', 17, 'liptak.gabor@luxmed.hu', '+36 20 234 5676', 3),
	('Dr. Nagy László', '83.jpg', 18, 'nagy.laszlo@luxmed.hu', '+36 30 876 5439', 3),
	('Dr. Horváth Zsófia', '84.jpg', 19, 'horvath.zsofia@luxmed.hu', '+36 70 234 5671', 3),
	('Dr. Lukács Péter', '85.jpg', 20, 'lukacs.peter@luxmed.hu', '+36 30 432 1099', 3),
	('Dr. Mészáros Éva', '86.jpg', 21, 'meszaros.eva@luxmed.hu', '+36 70 876 5437', 3),
	('Dr. Pintér Gabriella', '87.jpg', 21, 'pinter.gabriella@luxmed.hu', '+36 20 987 6548', 3),
	('Dr. Szegedi Zoltán', '88.jpg', 22, 'szegedi.zoltan@luxmed.hu', '+36 30 654 3216', 3),
	('Dr. Németh Tímea', '89.jpg', 23, 'nemeth.timea@luxmed.hu', '+36 70 765 4323', 3),
	('Dr. Kovács Péter', '90.jpg', 24, 'kovacs.peter@luxmed.hu', '+36 20 345 6789', 3),
	('Dr. Papp Ádám', '91.jpg', 3, 'papp.adam@luxmed.hu', '+36 20 234 5673', 4),
	('Dr. Kovács Eszter', '92.jpg', 4, 'kovacs.eszter@luxmed.hu', '+36 30 876 5436', 4),
	('Dr. Varga Zsuzsanna', '93.jpg', 5, 'varga.zsuzsanna@luxmed.hu', '+36 70 987 6549', 4),
	('Dr. Tóth Gábor', '94.jpg', 6, 'toth.gabor@luxmed.hu', '+36 20 876 5432', 4),
	('Dr. János László', '95.jpg', 7, 'janos.laszlo@luxmed.hu', '+36 30 234 5671', 4),
	('Dr. Balázs Katalin', '96.jpg', 7, 'balazs.katalin@luxmed.hu', '+36 70 234 5675', 4),
	('Dr. Horváth Tamás', '97.jpg', 8, 'horvath.tamas@luxmed.hu', '+36 20 765 4329', 4),
	('Dr. Farkas Róbert', '98.jpg', 9, 'farkas.robert@luxmed.hu', '+36 30 432 1096', 4),
	('Dr. Németh Mária', '99.jpg', 10, 'nemeth.maria@luxmed.hu', '+36 70 234 5674', 4),
	('Dr. Szegedi Béla', '100.jpg', 11, 'szegedi.bela@luxmed.hu', '+36 20 765 4326', 4),
	('Dr. Kocsis Ágnes', '101.jpg', 12, 'kocsis.agnes@luxmed.hu', '+36 30 987 6540', 4),
	('Dr. Tóth Dóra', '102.jpg', 13, 'toth.dora@luxmed.hu', '+36 70 432 1094', 4),
	('Dr. Lakatos Gábor', '103.jpg', 13, 'lakatos.gabor@luxmed.hu', '+36 20 987 6546', 4),
	('Dr. Cziráky Mária', '104.jpg', 14, 'cziraky.maria@luxmed.hu', '+36 30 765 4328', 4),
	('Dr. Németh Andrea', '105.jpg', 15, 'nemeth.andrea@luxmed.hu', '+36 70 234 5679', 4),
	('Dr. Kovács László', '106.jpg', 15, 'kovacs.laszlo@luxmed.hu', '+36 30 876 5437', 4),
	('Dr. Mészáros Andrea', '107.jpg', 16, 'meszaros.andrea@luxmed.hu', '+36 20 234 5678', 4),
	('Dr. Sándor Péter', '108.jpg', 16, 'sandor.peter@luxmed.hu', '+36 30 543 2108', 4),
	('Dr. Zsigmond Zoltán', '109.jpg', 17, 'zsigmond.zoltan@luxmed.hu', '+36 70 876 5438', 4),
	('Dr. Szabó László', '110.jpg', 18, 'szabo.laszlo@luxmed.hu', '+36 20 765 4324', 4),
	('Dr. Bognár Katalin', '111.jpg', 19, 'bognar.katalin@luxmed.hu', '+36 30 234 5675', 4),
	('Dr. Pécsi József', '112.jpg', 20, 'pecsi.jozsef@luxmed.hu', '+36 70 876 5430', 4),
	('Dr. Juhász Gábor', '113.jpg', 21, 'juhasz.gabor@luxmed.hu', '+36 20 432 1092', 4),
	('Dr. Gábor Andrea', '114.jpg', 21, 'gabor.andrea@luxmed.hu', '+36 30 654 3215', 4),
	('Dr. Fekete Miklós', '115.jpg', 22, 'fekete.miklos@luxmed.hu', '+36 70 234 5676', 4),
	('Dr. Nagy Edit', '116.jpg', 23, 'nagy.edit@luxmed.hu', '+36 30 567 8906', 4),
	('Dr. Sárközi János', '117.jpg', 24, 'sarkozi.janos@luxmed.hu', '+36 20 234 5672', 4),
	('Dr. Szabó Krisztián', '118.jpg', 3, 'szabo.krisztian@luxmed.hu', '+36 20 987 6547', 5),
	('Dr. Tóth Zsuzsanna', '119.jpg', 4, 'toth.zsuzsanna@luxmed.hu', '+36 30 765 4321', 5),
	('Dr. Farkas László', '120.jpg', 5, 'farkas.laszlo@luxmed.hu', '+36 70 987 6541', 5),
	('Dr. Varga Mónika', '121.jpg', 6, 'varga.monika@luxmed.hu', '+36 20 234 5675', 5),
	('Dr. Horváth Katalin', '122.jpg', 7, 'horvath.katalin@luxmed.hu', '+36 30 234 5676', 5),
	('Dr. László Péter', '123.jpg', 7, 'laszlo.peter@luxmed.hu', '+36 70 654 3217', 5),
	('Dr. Szűcs Ádám', '124.jpg', 8, 'szucs.adam@luxmed.hu', '+36 20 234 5679', 5),
	('Dr. Kovács Mária', '125.jpg', 9, 'kovacs.maria@luxmed.hu', '+36 30 765 4323', 5),
	('Dr. Tóth Anikó', '126.jpg', 10, 'toth.aniko@luxmed.hu', '+36 70 234 5670', 5),
	('Dr. Papp Gábor', '127.jpg', 11, 'papp.gabor@luxmed.hu', '+36 20 876 5432', 5),
	('Dr. Németh Andrea', '128.jpg', 12, 'nemeth.andrea@luxmed.hu', '+36 30 432 1091', 5),
	('Dr. Juhász Zoltán', '129.jpg', 13, 'juhasz.zoltan@luxmed.hu', '+36 70 234 5673', 5),
	('Dr. Kiss Mária', '130.jpg', 13, 'kiss.maria@luxmed.hu', '+36 20 876 5435', 5),
	('Dr. Bálint Tamás', '131.jpg', 14, 'balint.tamas@luxmed.hu', '+36 30 765 4320', 5),
	('Dr. Fodor Andrea', '132.jpg', 15, 'fodor.andrea@luxmed.hu', '+36 70 654 3215', 5),
	('Dr. Kocsis Zsuzsanna', '133.jpg', 15, 'kocsis.zsuzsanna@luxmed.hu', '+36 30 234 5677', 5),
	('Dr. Tóth Péter', '134.jpg', 16, 'toth.peter@luxmed.hu', '+36 20 432 1095', 5),
	('Dr. Szilágyi Gabriella', '135.jpg', 16, 'szilagyi.gabriella@luxmed.hu', '+36 30 765 4324', 5),
	('Dr. Móricz Zoltán', '136.jpg', 17, 'moricz.zoltan@luxmed.hu', '+36 70 234 5678', 5),
	('Dr. Varga Dóra', '137.jpg', 18, 'varga.dora@luxmed.hu', '+36 20 765 4320', 5),
	('Dr. Bencsik József', '138.jpg', 19, 'bencsik.jozsef@luxmed.hu', '+36 30 432 1092', 5),
	('Dr. Keresztes Tamás', '139.jpg', 20, 'keresztes.tamas@luxmed.hu', '+36 70 876 5434', 5),
	('Dr. Tóth Róbert', '140.jpg', 21, 'toth.robert@luxmed.hu', '+36 20 345 6780', 5),
	('Dr. Mészáros Katalin', '141.jpg', 21, 'meszaros.katalin@luxmed.hu', '+36 30 234 5673', 5),
	('Dr. Takács Zoltán', '142.jpg', 22, 'takacs.zoltan@luxmed.hu', '+36 70 987 6540', 5),
	('Dr. Nagy Anna', '143.jpg', 23, 'nagy.anna@luxmed.hu', '+36 20 765 4328', 5),
	('Dr. Somogyi Péter', '144.jpg', 24, 'somogyi.peter@luxmed.hu', '+36 30 234 5672', 5),
	('Dr. Varga Balázs', '145.jpg', 3, 'varga.balazs@luxmed.hu', '+36 20 345 6781', 6),
	('Dr. Kovács Mária', '146.jpg', 4, 'kovacs.maria@luxmed.hu', '+36 30 765 4327', 6),
	('Dr. Szabó Dániel ', '147.jpg', 5, 'szabo.daniel@luxmed.hu', '+36 70 432 1093', 6),
	('Dr. Kiss Róbert', '148.jpg', 6, 'kiss.robert@luxmed.hu', '+36 20 234 5673', 6),
	('Dr. Farkas Judit', '149.jpg', 7, 'farkas.judit@luxmed.hu', '+36 30 432 1094', 6),
	('Dr. Horváth Zoltán', '150.jpg', 7, 'horvath.zoltan@luxmed.hu', '+36 70 987 6544', 6),
	('Dr. Tóth András', '151.jpg', 8, 'toth.andras@luxmed.hu', '+36 20 234 5670', 6),
	('Dr. Papp Katalin', '152.jpg', 9, 'papp.katalin@luxmed.hu', '+36 30 765 4329', 6),
	('Dr. Sánta Zoltán', '153.jpg', 10, 'santa.zoltan@luxmed.hu', '+36 70 876 5438', 6),
	('Dr. László Anikó', '154.jpg', 11, 'laszlo.aniko@luxmed.hu', '+36 20 765 4326', 6),
	('Dr. Sándor Péter', '155.jpg', 12, 'sandor.peter@luxmed.hu', '+36 30 432 1098', 6),
	('Dr. Varga István', '156.jpg', 13, 'varga.istvan@luxmed.hu', '+36 70 234 5670', 6),
	('Dr. Juhász Andrea', '157.jpg', 13, 'juhasz.andrea@luxmed.hu', '+36 20 765 4322', 6),
	('Dr. Szilágyi Gábor', '158.jpg', 14, 'szilagyi.gabor@luxmed.hu', '+36 30 234 5679', 6),
	('Dr. Pécsi Júlia', '159.jpg', 15, 'pecsi.julia@luxmed.hu', '+36 70 876 5433', 6),
	('Dr. Mészáros Tamás', '160.jpg', 15, 'meszaros.tamas@luxmed.hu', '+36 20 432 1095', 6),
	('Dr. Kovács Zoltán', '161.jpg', 16, 'kovacs.zoltan@luxmed.hu', '+36 30 234 5671', 6),
	('Dr. Pál Zsófia', '162.jpg', 16, 'pal.zsofia@luxmed.hu', '+36 70 765 4320', 6),
	('Dr. Fodor Éva', '163.jpg', 17, 'fodor.eva@luxmed.hu', '+36 20 345 6782', 6),
	('Dr. Sárközi László', '164.jpg', 18, 'sarkozi.laszlo@luxmed.hu', '+36 30 765 4325', 6),
	('Dr. Tóth Klára', '165.jpg', 19, 'toth.klara@luxmed.hu', '+36 70 432 1090', 6),
	('Dr. Nagy Imre', '166.jpg', 20, 'nagy.imre@luxmed.hu', '+36 30 876 5435', 6),
	('Dr. Horváth László', '167.jpg', 21, 'horvath.laszlo@luxmed.hu', '+36 20 765 4327', 6),
	('Dr. Rácz Petra', '168.jpg', 21, 'racz.petra@luxmed.hu', '+36 30 234 5674', 6),
	('Dr. Kis Gábor', '169.jpg', 22, 'kis.gabor@luxmed.hu', '+36 70 987 6542', 6),
	('Dr. Kiss Alexandra', '170.jpg', 23, 'kiss.alexandra@luxmed.hu', '+36 30 765 4326', 6),
	('Dr. Szabó Gábor', '171.jpg', 24, 'szabo.gabor@luxmed.hu', '+36 20 876 5431', 6),
	('Dr. Kovács Tamás', '172.jpg', 3, 'kovacs.tamas@luxmed.hu', '+36 20 234 5679',  7),
	('Dr. Németh László', '173.jpg', 4, 'nemeth.laszlo@luxmed.hu', '+36 30 432 1095', 7),
	('Dr. Varga Andrea', '174.jpg', 5, 'varga.andrea@luxmed.hu', '+36 70 234 5678', 7),
	('Dr. Kiss Mária', '175.jpg', 6, 'kiss.maria@luxmed.hu', '+36 20 876 5433', 7),
	('Dr. Juhász Zsuzsa', '176.jpg', 7, 'juhasz.zsuzsa@luxmed.hu', '+36 30 765 4329', 7),
	('Dr. Horváth Tamás', '177.jpg', 7, 'horvath.tamas@luxmed.hu', '+36 70 234 5677', 7),
	('Dr. Pécsi Krisztián', '178.jpg', 8, 'pecsi.krisztian@luxmed.hu', '+36 20 345 6789', 7),
	('Dr. Farkas Andrea', '179.jpg', 9, 'farkas.andrea@luxmed.hu', '+36 30 234 5676', 7),
	('Dr. Németh Péter', '180.jpg', 10, 'nemeth.peter@luxmed.hu', '+36 70 765 4323', 7),
	('Dr. Kovács Ágnes', '181.jpg', 11, 'kovacs.agnes@luxmed.hu', '+36 20 432 1098', 7),
	('Dr. Tóth Katalin', '182.jpg', 12, 'toth.katalin@luxmed.hu', '+36 30 234 5670', 7),
	('Dr. Varga Gábor', '183.jpg', 13, 'varga.gabor@luxmed.hu', '+36 70 432 1096', 7),
	('Dr. Fodor Éva', '184.jpg', 13, 'fodor.eva@luxmed.hu', '+36 20 765 4327', 7),
	('Dr. Szabó Zoltán', '185.jpg', 14, 'szabo.zoltan@luxmed.hu', '+36 30 987 6541', 7),
	('Dr. Tóth Andrea', '186.jpg', 15, 'toth.andrea@luxmed.hu', '+36 70 234 5673', 7),
	('Dr. Tóth Mária', '187.jpg', 15, 'toth.maria@luxmed.hu', '+36 20 765 4325', 7),
	('Dr. Papp Zsuzsanna', '188.jpg', 16, 'papp.zsuzsanna@luxmed.hu', '+36 30 765 4324', 7),
	('Dr. Sárközi Gábor', '189.jpg', 16, 'sarkozi.gabor@luxmed.hu', '+36 70 432 1094', 7),
	('Dr. Kálmán János', '190.jpg', 17, 'kalman.janos@luxmed.hu', '+36 30 234 5671', 7),
	('Dr. Tóth László', '191.jpg', 18, 'toth.laszlo@luxmed.hu', '+36 70 876 5430', 7),
	('Dr. Varga Róbert', '192.jpg', 19, 'varga.robert@luxmed.hu', '+36 20 987 6546', 7),
	('Dr. Kis Andrea', '193.jpg', 20, 'kis.andrea@luxmed.hu', '+36 30 234 5675', 7),
	('Dr. Bognár Péter', '194.jpg', 21, 'bognar.peter@luxmed.hu', '+36 70 432 1093', 7),
	('Dr. Gábor Mária', '195.jpg', 21, 'gabor.maria@luxmed.hu', '+36 20 765 4321', 7),
	('Dr. Bencsik Zoltán', '196.jpg', 22, 'bencsik.zoltan@luxmed.hu', '+36 30 987 6543', 7),
	('Dr. Mészáros Gábor', '197.jpg', 23, 'meszaros.gabor@luxmed.hu', '+36 70 234 5679', 7),
	('Dr. Tóth Zoltán', '198.jpg', 24, 't oth.zoltan@luxmed.hu', '+36 30 765 4328', 7),
	('Dr. Tóth Tamás', '199.jpg', 3, 'toth.tamas@luxmed.hu', '+36 20 765 4329', 8),
	('Dr. Szabó Katalin', '200.jpg', 4, 'szabo.katalin@luxmed.hu', '+36 30 432 1097', 8),
	('Dr. Farkas Zoltán', '201.jpg', 5, 'farkas.zoltan@luxmed.hu', '+36 70 765 4321', 8),
	('Dr. Kiss Gabriella', '202.jpg', 6, 'kiss.gabriella@luxmed.hu', '+36 20 432 1094', 8),
	('Dr. Pál Mária', '203.jpg', 7, 'pal.maria@luxmed.hu', '+36 30 234 5675', 8),
	('Dr. László Zoltán', '204.jpg', 7, 'laszlo.zoltan@luxmed.hu', '+36 70 432 1096', 8),
	('Dr. Bognár Krisztina', '205.jpg', 8, 'bognar.krisztina@luxmed.hu', '+36 20 234 5673', 8),
	('Dr. Horváth Ágnes', '206.jpg', 9, 'horvath.agnes@luxmed.hu', '+36 30 234 5679', 8),
	('Dr. Kovács Imre', '207.jpg', 10, 'kovacs.imre@luxmed.hu', '+36 70 987 6545', 8),
	('Dr. Szabó Tímea', '208.jpg', 11, 'szabo.timea@luxmed.hu', '+36 20 765 4328', 8),
	('Dr. Németh Gábor', '209.jpg', 12, 'nemeth.gabor@luxmed.hu', '+36 30 432 1099', 8),
	('Dr. Pécsi Anita', '210.jpg', 13, 'pecsi.anita@luxmed.hu', '+36 70 234 5678', 8),
	('Dr. Keresztes József', '211.jpg', 13, 'keresztes.jozsef@luxmed.hu', '+36 20 345 6780', 8),
	('Dr. Juhász Andrea', '212.jpg', 14, 'juhasz.andrea@luxmed.hu', '+36 30 765 4322', 8),
	('Dr. Fodor Tamás', '213.jpg', 15, 'fodor.tamas@luxmed.hu', '+36 70 987 6546', 8),
	('Dr. Tóth Zoltán', '214.jpg', 15, 'toth.zoltan@luxmed.hu', '+36 20 234 5678', 8),
	('Dr. Sárközi Katalin', '215.jpg', 16, 'sarkozi.katalin@luxmed.hu', '+36 30 234 5676', 8),
	('Dr. Varga Krisztina', '216.jpg', 16, 'varga.krisztina@luxmed.hu', '+36 70 432 1097', 8),
	('Dr. Farkas Zoltán', '217.jpg', 17, 'farkas.zoltan@luxmed.hu', '+36 20 345 6785', 8),
	('Dr. Papp Mária', '218.jpg', 18, 'papp.maria@luxmed.hu', '+36 30 234 5672', 8),
	('Dr. Németh Balázs', '219.jpg', 19, 'nemeth.balazs@luxmed.hu', '+36 70 432 1093', 8),
	('Dr. Varga András', '220.jpg', 20, 'varga.andras@luxmed.hu', '+36 20 765 4323', 8),
	('Dr. Juhász Gábor', '221.jpg', 21, 'juhasz.gabor@luxmed.hu', '+36 30 234 5674', 8),
	('Dr. Kovács Zsuzsanna', '222.jpg', 21, 'kovacs.zsuzsanna@luxmed.hu', '+36 70 765 4320', 8),
	('Dr. Tóth Gábor', '223.jpg', 22, 'toth.gabor@luxmed.hu', '+36  20 432 1092', 8),
	('Dr. Bencsik László', '224.jpg', 23, 'bencsik.laszlo@luxmed.hu', '+36 30 234 5673', 8),
	('Dr. Nagy András', '225.jpg', 24, 'nagy.andrea@luxmed.hu', '+36 70 432 1092', 8);

-- -----------------------------------------------------
-- Table `luxmed`.`Velemeny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luxmed`.`Velemeny` (
  `velemeny_id` INT NOT NULL AUTO_INCREMENT,
  `velemeny_text` VARCHAR(45) NOT NULL,
  `felhasznalo_id` INT NOT NULL,
  `orvos_id` INT NOT NULL,
  `bejegyzes_ido` DATETIME NOT NULL,
  PRIMARY KEY (`velemeny_id`),
  INDEX `fk_Velemeny_Felhasznalo1_idx` (`felhasznalo_id` ASC) VISIBLE,
  INDEX `fk_Velemeny_Orvos1_idx` (`orvos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Velemeny_Felhasznalo1`
    FOREIGN KEY (`felhasznalo_id`)
    REFERENCES `luxmed`.`Felhasznalo` (`felhasznalo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Velemeny_Orvos1`
    FOREIGN KEY (`orvos_id`)
    REFERENCES `luxmed`.`Orvos` (`orvos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luxmed`.`Szolgaltatas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luxmed`.`Szolgaltatas` (
  `szolgaltatas_id` INT NOT NULL AUTO_INCREMENT,
  `szolgaltatas_nev` VARCHAR(45) NOT NULL,
  `szakterulet_id` INT NOT NULL,
  `ar` INT NOT NULL,
  PRIMARY KEY (`szolgaltatas_id`),
  INDEX `fk_Szolgaltatas_Szakterulet1_idx` (`szakterulet_id` ASC) VISIBLE,
  CONSTRAINT `fk_Szolgaltatas_Szakterulet1`
    FOREIGN KEY (`szakterulet_id`)
    REFERENCES `luxmed`.`Szakterulet` (`szakterulet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Dummy `luxmed`.`Szolgaltatas`
-- -----------------------------------------------------

INSERT INTO `luxmed`.`Szolgaltatas` (`szolgaltatas_id`, `szolgaltatas_nev`, `szakterulet_id`, `ar`) VALUES
(1, 'Belgyógyászati vizsgálat', 3, 30000),
(2, 'Belgyógyászati műtét', 3, 120000),
(3, 'Bőrgyógyászati vizsgálat', 4, 25000),
(4, 'Bőrgyógyászati műtét', 4, 100000),
(5, 'Dietetikai tanácsadás', 5, 10000),
(7, 'Endokrinológiai vizsgálat', 6, 35000),
(8, 'Endokrinológiai műtét', 6, 180000),
(9, 'Érsebészeti vizsgálat', 7, 40000),
(10, 'Érsebészeti műtét', 7, 250000),
(11, 'Fül-Orr-Gégészeti vizsgálat', 8, 28000),
(12, 'Fül-Orr-Gégészeti műtét', 8, 130000),
(13, 'Gasztroenterológiai vizsgálat', 9, 35000),
(14, 'Gasztroenterológiai műtét', 9, 200000),
(15, 'Gyermeksebészeti vizsgálat', 10, 30000),
(16, 'Gyermeksebészeti műtét', 10, 150000),
(17, 'Hematológiai vizsgálat', 11, 32000),
(18, 'Hematológiai műtét', 11, 190000),
(19, 'Idegsebészeti vizsgálat', 12, 45000),
(20, 'Idegsebészeti műtét', 12, 300000),
(21, 'Kardiológiai vizsgálat', 13, 40000),
(22, 'Szívműtét', 13, 250000),
(23, 'Kézsebészeti vizsgálat', 14, 35000),
(24, 'Kézműtét', 14, 150000),
(25, 'Neurológiai vizsgálat', 15, 30000),
(26, 'Neurológiai műtét', 15, 220000),
(27, 'Nőgyógyászati vizsgálat', 16, 28000),
(28, 'Nőgyógyászati műtét', 16, 160000),
(29, 'Ortopédiai vizsgálat', 17, 35000),
(30, 'Ortopédiai műtét', 17, 250000),
(31, 'Plasztikai sebészeti vizsgálat', 18, 50000),
(32, 'Plasztikai műtét', 18, 350000),
(33, 'Pulmonológiai vizsgálat', 19, 35000),
(34, 'Pulmonológiai műtét', 19, 180000),
(35, 'Reumatológiai vizsgálat', 20, 30000),
(36, 'Reumatológiai műtét', 20, 180000),
(37, 'Sebészeti vizsgálat', 21, 40000),
(38, 'Sebészeti műtét', 21, 250000),
(39, 'Szemészeti vizsgálat', 22, 25000),
(40, 'Szemműtét', 22, 150000),
(41, 'Szülészeti vizsgálat', 23, 35000),
(42, 'Szülés (programozott)', 23, 200000),
(43, 'Urológiai vizsgálat', 24, 30000),
(44, 'Urológiai műtét', 24, 220000);


-- -----------------------------------------------------
-- Table `luxmed`.`Idopont`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luxmed`.`Idopont` (
  `idopont_id` INT NOT NULL AUTO_INCREMENT,
  `ido` DATETIME NOT NULL,
  `felhasznalo_id` INT NOT NULL,
  `orvos_id` INT NOT NULL,
  `korhaz_id` INT NOT NULL,
  `szolgaltatas_id` INT NOT NULL,
  PRIMARY KEY (`idopont_id`),
  INDEX `fk_Idopont_Felhasznalo_idx` (`felhasznalo_id` ASC) VISIBLE,
  INDEX `fk_Idopont_Orvos1_idx` (`orvos_id` ASC) VISIBLE,
  INDEX `fk_Idopont_Korhaz1_idx` (`korhaz_id` ASC) VISIBLE,
  INDEX `fk_Idopont_Szolgaltatas1_idx` (`szolgaltatas_id` ASC) VISIBLE,
  CONSTRAINT `fk_Idopont_Felhasznalo`
    FOREIGN KEY (`felhasznalo_id`)
    REFERENCES `luxmed`.`Felhasznalo` (`felhasznalo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Idopont_Orvos1`
    FOREIGN KEY (`orvos_id`)
    REFERENCES `luxmed`.`Orvos` (`orvos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Idopont_Korhaz1`
    FOREIGN KEY (`korhaz_id`)
    REFERENCES `luxmed`.`Korhaz` (`korhaz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Idopont_Szolgaltatas1`
    FOREIGN KEY (`szolgaltatas_id`)
    REFERENCES `luxmed`.`Szolgaltatas` (`szolgaltatas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
